const IS_LOADING_COIN_NEWS = 'IS_LOADING_COIN_NEWS',
      IS_LOADING_COINS = 'IS_LOADING_COINS',
      IS_LOADING_USER = 'IS_LOADING_USER',
      IS_LOADING_USER_FAVS = 'IS_LOADING_USER_FAVS'

export {
    IS_LOADING_COIN_NEWS,
    IS_LOADING_COINS,
    IS_LOADING_USER,
    IS_LOADING_USER_FAVS
}