const IS_ERROR_LOADING_COINS = 'IS_ERROR_LOADING_COINS',
      IS_ERROR_LOADING_COIN_NEWS = 'IS_ERROR_LOADING_COIN_NEWS',
      IS_ERROR_LOADING_USER = 'IS_ERROR_LOADING_USER',
      RETRIEVE_COINS = 'RETRIEVE_COINS',
      RETRIEVE_COIN_NEWS = 'RETRIEVE_COIN_NEWS',
      RETRIEVE_USER_FAVS = 'RETRIEVE_USER_FAVS'

export {
    IS_ERROR_LOADING_COINS,
    IS_ERROR_LOADING_COIN_NEWS,
    IS_ERROR_LOADING_USER,
    RETRIEVE_COINS,
    RETRIEVE_COIN_NEWS,
    RETRIEVE_USER_FAVS
}